### PR TITLE
Styling Changes to Generate Pattern

### PR DESCRIPTION
**Pull request by karthikvetrivel**
Screen Shot 2020-08-12 at 10 03 06 AM

### CODE REVIEW

**Comment by jConquest** [comment]
Hey @karthikvetrivel unfortunately the gui scaling is not working on windows. can you manually set the window size to be about 10% larger on the horizontal axis. Also, can we update the text of the window to have the numbers written as real numbers (ie 1.0)

**Comment by jConquest** [comment]
I also made a push to this branch removing the target folder to prevent adding the log files and executable to the master

**Comment by karthikvetrivel** [comment]
Alright, I added the real numbers and made the horizontal scaling a little larger. Let me know how that looks on Windows?

**Comment by jConquest** [comment]
Looks great!

**Pull request merged**
