### PR TITLE
Directory structure update

### PR DESCRIPTION
**Pull request by stevecl5**
Contained in this branch:
- New directory structure for workbench files
- Updated data model, including new Project and Simulation classes
- Improved class and package organization
- Added Javadoc comments for several classes
- Other bug fixes and general improvements

### CODE REVIEW

**Comment by stiber** [comment]
Let me know if you want my input; otherwise, I see that @king-shak is the reviewer for this.

**Review by king-shak — CHANGES_REQUESTED** [review]
Overall, everything looks good and works as described by Steven! It was certainly nice as I worked through my testing to see that everything was properly organized rather than being dumped into my home folder! All I have are a few nit-picks on the names for files and some additional points to mention.

## Filename Nit-Picks

 * Could `simName_cmdOutput.txt` (`simName` is the name of the sim provided by the user.) be renamed to `simName_buildStatus.txt`? I feel it makes more sense, since this contains the output from the commands which clone the repo and build the sim, so you'd only look at this file if the build failed (executable was not there) or the repo didn't even clone to see what specifically went wrong.
 * Could the `UniversalProvenance.ttl` file created for each project be renamed to `ProjectNameProvenance.ttl` where `ProjectName` is the user-defined project name? I feel this would makes things easier for the user say, if they have multiple ProVis tabs open, so they know which project the provenance file belongs to.

## Additional Points

 * The Simulation Runtime Dialog for the previous version would only show the events for the current running simulation, however this one shows the entire history. Not sure whether this was intended or not, but this made things a little confusing for me when I wanted to go through the events for the sim I was currently running.
 * The way it generates graphs seems to be different. In the image below, the build from `directory-structure-update` is on the left, the one from `master` on the right. For both of them in my testing I ran 3 sims from the same build of BrainGrid using the same config files. The new one creates the entity nodes for the config files *for each activity node* (repeating them), while the old one (the build from `master`) created the entity nodes for the config files *once*, linking them to *all* of the activity nodes which used it. As you can tell, the resulting graph doesn't look good. However, I'm not sure which version is desired. One obviously looks better than the other, but I think the one that looks worse may be more correct since you can immediately tell those 3 sims use the same config files. If this is something that needs fixing, it would likely be a separate issue we would create for someone to work on. My guess this behavior is a result of cleaning up how the files are organized which may have somehow affected how the provenance files are created, resulting in this sort of graph.

Difference in Graph Generation

 * Lastly, for me personally, the delay in transferring the files needed for the script to run the sim wasn't noticeable. Maybe it's because I have a better connection to the Linux Labs where I was doing my testing; I just figured this was worth mentioning.

Otherwise, nice work!

**Comment by stevecl5** [comment]
> Could `simName_cmdOutput.txt` (`simName` is the name of the sim provided by the user.) be renamed to `simName_buildStatus.txt`? I feel it makes more sense, since this contains the output from the commands which clone the repo and build the sim, so you'd only look at this file if the build failed (executable was not there) or the repo didn't even clone to see what specifically went wrong.

Looking into the Script class, output is redirected to `cmdOutput.txt` (previously named `output.txt`) any time a bash command is added to the script using `executeProgram` or `addVerbatimStatement`. While cloning/updating the repo and building the executable are things we might need to check on, I don't think we should assume that is always the case. There are also commands for creating/changing directories which could potentially fail and are not associated with "buildStatus". Also, from a modularity perspective, I think it's best to stick with the general name "cmdOutput" since this is defined in the Script class (the "script" package doesn't know anything about builds or repos).

> Could the `UniversalProvenance.ttl` file created for each project be renamed to `ProjectNameProvenance.ttl` where `ProjectName` is the user-defined project name? I feel this would makes things easier for the user say, if they have multiple ProVis tabs open, so they know which project the provenance file belongs to.

Done.

> The Simulation Runtime Dialog for the previous version would only show the events for the current running simulation, however this one shows the entire history. Not sure whether this was intended or not, but this made things a little confusing for me when I wanted to go through the events for the sim I was currently running.

Previously, new workbench managers were created as needed, so there was no need to clear the accumulated messages. Now, there is just one workbench manager, so it's necessary to clear the messages from the previous simulation. To resolve this, I added a private `clearMessages` method which is called by `newSimulation` in `WorkbenchManager`.

Thinking long term, a lot of the simulation stuff in `WorkbenchManager` would probably fit better in `SimStartWiz` including the message accumulator. This is something I thought of doing but never got around to. That is a bigger change than is needed for this particular issue, but it's something we should discuss.

> The way it generates graphs seems to be different. In the image below, the build from `directory-structure-update` is on the left, the one from `master` on the right. For both of them in my testing I ran 3 sims from the same build of BrainGrid using the same config files. The new one creates the entity nodes for the config files _for each activity node_ (repeating them), while the old one (the build from `master`) created the entity nodes for the config files _once_, linking them to _all_ of the activity nodes which used it. As you can tell, the resulting graph doesn't look good. However, I'm not sure which version is desired. One obviously looks better than the other, but I think the one that looks worse may be more correct since you can immediately tell those 3 sims use the same config files. If this is something that needs fixing, it would likely be a separate issue we would create for someone to work on. My guess this behavior is a result of cleaning up how the files are organized which may have somehow affected how the provenance files are created, resulting in this sort of graph.

In `master`, using config files with the same name (whether or not they are actually the same) results in the config files being overwritten each time you run a simulation. This is why the provenance points to the same absolute file path for all of the files (even though technically only the final artifact actually exists).

In `directory-structure-update`, the config files are separated into simulation folders. This is more accurate because they are separate artifacts (even if they have the same name). You can always do a diff on the files through ProVis to see whether or not the contents are actually the same.

> Lastly, for me personally, the delay in transferring the files needed for the script to run the sim wasn't noticeable. Maybe it's because I have a better connection to the Linux Labs where I was doing my testing; I just figured this was worth mentioning.

Cool. Good to know!

**Comment by king-shak** [comment]
Alright, all looks good!

**Review by king-shak — APPROVED** [review]
Alright, all looks good!

**Pull request merged**
